### ISSUE TITLE
ERROR: On worker 2: can't mix implict Params with explict rule from Optimisers.jl

### ISSUE THREAD

**Issue by wanghf810501** [ranafi/CYCLOPS-2.0#3]
Hi,
I encountered  the following error message when I try to use CYCLOS 2.0:
ERROR: On worker 2:
can't mix implict Params with explict rule from Optimisers.jl
To use Flux.params(m) in train!, the 4th argument must be from the old Flux.Optimise sub-module.
But better to use the new explicit style, in which m itself is the 2nd argument.

So I change every Flux.train!(x -> mse(m(x), x[1:m.o]), Flux.params(m.S_OH, m.B, m.B_OH, m.L1, m.L2), zip(gea_vectorized), ADAM(μA, β), cb = () -> ()) in CYCLOPS.jl
to  Flux.train!(x -> mse(m(x), x[1:m.o]), m, zip(gea_vectorized), ADAM(μA, β), cb = () -> ()),
is that correct?

**Comment by wanghf810501** [comment]
After I made the modification, the following warnings comes:
      From worker 28:	└ @ Optimisers ~/.julia/packages/Optimisers/yDIWk/src/interface.jl:32
      From worker 32:	┌ Warning: setup found no trainable parameters in this model
      From worker 32:	└ @ Optimisers ~/.julia/packages/Optimisers/yDIWk/src/interface.jl:32
      From worker 34:	┌ Warning: setup found no trainable parameters in this model
      From worker 34:	└ @ Optimisers ~/.julia/packages/Optimisers/yDIWk/src/interface.jl:32
      From worker 24:	┌ Warning: setup found no trainable parameters in this model
      From worker 24:	└ @ Optimisers ~/.julia/packages/Optimisers/yDIWk/src/interface.jl:32
      From worker 48:	┌ Warning: setup found no trainable parameters in this model
      From worker 48:	└ @ Optimisers ~/.julia/packages/Optimisers/yDIWk/src/interface.jl:32
........

**Comment by JanHammarlund** [comment]
Hello, which version of Julia are you using. The current version of CYCLOPS is meant for Julia 1.6. Please also see the package versions listed the documentation. Thank you.

**Comment by wanghf810501** [comment]
I see, I am using julia 1.11.1

**Comment by wanghf810501** [comment]
Now change to julia 1.6.6 and the package versions listed in the documentation, then I get the following error message when run CYCLOPS.Align:
ERROR: UndefVarError: writeshortest not defined
Stacktrace:
I have try to "add Parsers@v2.2.4" as someone suggested, but it does not work!

**Comment by JanHammarlund** [comment]
Are you on a Mac or PC? This is the first time I have encountered this error. You may also want to uninstall Julia fully and the associated data, then reinstall Julia 1.6.6. Please provide a shared link to a folder with your script and data.

**Comment by wanghf810501** [comment]
Thank you very much for your help! It works perfectly now.
